### PR TITLE
fix: add coreuils build dependency

### LINKED ISSUE #9: Test check-regexprops fails with "mktemp: ./check-regexprops 28: FSUM7351 not found"
mktemp is part of coreutils, so we will need coreutils as a dependency.

### PR DESCRIPTION
**Pull request by dougburns**
Fixes #9.

### CODE REVIEW

**Comment by dougburns** [comment]
This fix exposes more build issues which will need to be addressed before it is committed.
#10 Multiple test suites report separate results and zopen_check_results doesn't process the output correctly
#12 Possible loop in multiple tests

**Comment by dougburns** [comment]
Fixes #12 - some issues fixed, some temporarily worked around. See the details in the issue.
Fixes #10 - zopen_check_results updated.

**Comment by dougburns** [comment]
@IgorTodorovskiIBM @MikeFultonDev 
This is now ready for review is either of you can spare a bit of time.
I don't have authority to assign reviewers.

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM, thanks!

**Comment by dougburns** [comment]
@IgorTodorovskiIBM Thanks for the review.
If you're happy, could you merge this as I don't have write access?

**Pull request merged**
